[package]
name = "mai-auto-sheet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html_parser = "0.6.2"
thiserror = "1.0.30"
html2text = "0.3.1"
